name: 'Dagster Cloud CI'
description: |
  'Builds and pushes Dagster repo Docker images and updates the corresponding Dagster Cloud repo locations.'
inputs:
  dagit-url:
    description: 'Dagster Cloud Dagit URL'
    required: true
  api-token:
    description: 'Cloud Agent API token'
    required: true

  location-file:
    description: 'Path to the locations.yaml file defining the repo locations to update'
    required: true
    default: 'locations.yaml'

  image-tag:
    description: 'Tag for the built Docker images, defaults to first 6 chars of git hash'
    required: false
    default: ''

  parallel:
    description: 'Whether to build and push all Docker images in parallel'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
