name: 'Dagster Cloud CI'
description: |
  'Builds and pushes Dagster repo Docker images and updates the corresponding Dagster Cloud repo locations.'
inputs:
  dagit-url:
    description: 'Dagster Cloud Dagit URL'
    required: true
  api-token:
    description: 'Cloud Agent API token'
    required: true

  location-name:
    description: 'Repo Location name'
    required: true
  python-file:
    description: 'Python file where the repository lives in the built Docker image'
    required: false
    default: ''
  package-name:
    description: 'Python package where the repository lives in the built Docker image'
    required: false
    default: ''

  build-path:
    description: 'Path to the directory containing the Dockerfile from the root of the repository'
    required: true
    default: '.'
  registry:
    description: 'Docker image registry location'
    required: true

  image-tag:
    description: 'tag for the built Docker image, defaults to first 6 chars of git hash'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
