name: Test Dagster Cloud CI action
on: push

jobs:
  dagster-cloud-update-locations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run Dagster Cloud CI action
        uses: ./
        with:
          location-file: ./test/locations.yaml
          dagit-url: https://elementl.dogfood.dagster.cloud/dev
          api-token: ${{ secrets.DAGSTER_AGENT_TOKEN }}